### ISSUE TITLE
Syncing with Split Left / Right 

### ISSUE THREAD

**Issue by DeadIntermediate** [pusher/atom-pair#101]
I have made a session with a friend and it works amazingly! But I want to know that if left say, I have my file, let says A.yml is on the left and my friend pulls a file into the session called B.yml and I am editing A.yml and he editing B.yml in different tabs. 

Is there a way I can have A.yml on left side and his B.yml on the right, so I can edit my A.yml file while he works on his B.yml file.

**Comment by kn100** [comment]
Unfortunately not right now, sorry!
