### ISSUE TITLE
"GOTO" for collaborators?

### ISSUE THREAD

**Issue by natdm** [pusher/atom-pair#107]
Not sure if this has been discussed - it's not an open issue that I found.

Will there ever be a way to have some way to go to a collaborator cursor? I've found if I open atom-pair in a bigger project, I have no idea where my collaborators are typing. This seems to really restrict what I'm comfortable doing with atom-pair. 

Some way to go to where their cursors are, or see what they last did - maybe with a background color on text that you didn't type, during the pairing session?

**Comment by kn100** [comment]
Thanks for the suggestion!
