### ISSUE TITLE
Deprecated selector in `atom-pair/styles/atom_pair.less`

### ISSUE THREAD

**Issue by YagoQuinoy** [pusher/atom-pair#111]
In `atom-pair/styles/atom_pair.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`

**Comment by leesio** [comment]
Fix merged into master (3abdc4739ae6adb29d59b3543896ba7fdc9d093f)
Tagged as release v2.0.12 and published to apm
Thanks to @Grot4x for the PR
