### ISSUE TITLE
Deprecated selector in `atom-pair\styles\atom_pair.less`

### ISSUE THREAD

**Issue by marquebr** [pusher/atom-pair#113]
In `atom-pair\styles\atom_pair.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .aqua` => `atom-text-editor.editor .syntax--aqua`

* `atom-text-editor::shadow .aquamarine` => `atom-text-editor.editor .aquamarine`

* `atom-text-editor::shadow .beige` => `atom-text-editor.editor .beige`

* `atom-text-editor::shadow .bisque` => `atom-text-editor.editor .bisque`

* `atom-text-editor::shadow .black` => `atom-text-editor.editor .syntax--black`

* `atom-text-editor::shadow .blanchedalmond` => `atom-text-editor.editor .blanchedalmond`

* `atom-text-editor::shadow .blue` => `atom-text-editor.editor .syntax--blue`

* `atom-text-editor::shadow .blueviolet` => `atom-text-editor.editor .blueviolet`

* `atom-text-editor::shadow .brown` => `atom-text-editor.editor .brown`

* `atom-text-editor::shadow .burlywood` => `atom-text-editor.editor .burlywood`

* `atom-text-editor::shadow .cadetblue` => `atom-text-editor.editor .cadetblue`

* `atom-text-editor::shadow .chartreuse` => `atom-text-editor.editor .chartreuse`

* `atom-text-editor::shadow .chocolate` => `atom-text-editor.editor .chocolate`

* `atom-text-editor::shadow .coral` => `atom-text-editor.editor .coral`

* `atom-text-editor::shadow .cornflowerblue` => `atom-text-editor.editor .cornflowerblue`

* `atom-text-editor::shadow .cornsilk` => `atom-text-editor.editor .cornsilk`

* `atom-text-editor::shadow .crimson` => `atom-text-editor.editor .crimson`

* `atom-text-editor::shadow .cyan` => `atom-text-editor.editor .syntax--cyan`

* `atom-text-editor::shadow .darkblue` => `atom-text-editor.editor .darkblue`

* `atom-text-editor::shadow .darkcyan` => `atom-text-editor.editor .darkcyan`

* `atom-text-editor::shadow .darkgoldenrod` => `atom-text-editor.editor .darkgoldenrod`

* `atom-text-editor::shadow .darkgray` => `atom-text-editor.editor .darkgray`

* `atom-text-editor::shadow .darkgreen` => `atom-text-editor.editor .darkgreen`

* `atom-text-editor::shadow .darkkhaki` => `atom-text-editor.editor .darkkhaki`

* `atom-text-editor::shadow .darkmagenta` => `atom-text-editor.editor .darkmagenta`

* `atom-text-editor::shadow .darkolivegreen` => `atom-text-editor.editor .darkolivegreen`

* `atom-text-editor::shadow .darkorange` => `atom-text-editor.editor .darkorange`

* `atom-text-editor::shadow .darkorchid` => `atom-text-editor.editor .darkorchid`

* `atom-text-editor::shadow .darkred` => `atom-text-editor.editor .darkred`

* `atom-text-editor::shadow .darksalmon` => `atom-text-editor.editor .darksalmon`

* `atom-text-editor::shadow .darkseagreen` => `atom-text-editor.editor .darkseagreen`

* `atom-text-editor::shadow .darkslateblue` => `atom-text-editor.editor .darkslateblue`

* `atom-text-editor::shadow .darkslategray` => `atom-text-editor.editor .darkslategray`

* `atom-text-editor::shadow .darkturquoise` => `atom-text-editor.editor .d

**Comment by danielperez9430** [comment]
the same error

**Comment by MrFiregore** [comment]
remove all ::shadow and reopen atom

**Comment by Aetherall** [comment]
@firegore2 Where do I may remove ::shadow? Thx

**Comment by ghost** [comment]
Due to the inactivity of the repository collaborators regarding [this fix](https://github.com/pusher/atom-pair/pull/112), many **atom-pair** users have uninstalled this package and switched to a well-maintained version [**atom-pair-less**](https://atom.io/packages/atom-pair-less) which runs the same, but without persistent deprecations.

**Comment by jayjun** [comment]
Hi @jpatel531, @hot-leaf-juice, @Grot4x and @ewmy. Can we fix this?

**Comment by leesio** [comment]
Fix merged into master (3abdc4739ae6adb29d59b3543896ba7fdc9d093f)
Tagged as release v2.0.12 and published to apm

Thanks to @Grot4x for the PR
