### ISSUE TITLE
Save paired file

### ISSUE THREAD

**Issue by rkm** [pusher/atom-pair#124]
Would it be possible to save the remote file when doing Ctrl+S in a pair session? Currently the dialogue just pops up to save a local copy as far as I can see?

**Comment by a-eid** [comment]
+1

**Comment by kn100** [comment]
Each party can save their own individual versions, however they will fall out of sync unless both parties save again when they are done collaborating. I'd recommend having one party own the files who is responsible for saving, and the second party simply joins when they need to, but saves nothing locally.
