### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ZateFeto** [pusher/atom-pair#131]
Followed all the steps and it doesn't work, as soon as i enter the session or the other pc enters the session, nothing happens.. no errors .. nothing at all as if no command were givin after pasting the session id and pressing enter.

Can you do a more detailed guide/video please?

**Comment by kn100** [comment]
Please specify some further information. What version of atom? How did you get the plugin? etc

**Comment by ZateFeto** [comment]
Atom version : 1.19.5 x64

Getting the plugin : file>Setting>packages > search for atompair > installed

I did follow all the steps mentioned by atom pair and still not working

Directly after i paste the session id in the join existing pairing session tab.. Nothing happens latterly (no popups/no errors/nocrash/just null)

Thats ofc after setting up 2 pusher accounts for the 2 different pc's and made sure of the app setting enabling events, And copied new key and secret.

**Comment by ZateFeto** [comment]
Bump..

**Comment by ZateFeto** [comment]
IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:107311
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher-js-client-auth.js:111 You are using PusherJS client authentication. Never ever use this for a production application, as it would expose your secret keys.
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher-js-client-auth.js:111
C:\Users\ZateFeto BDK\.atom\packages\floobits\lib\floobits.js:145 updated user prefs Object
<embedded>:180187 No available version compatible with the installed Atom version: 1.19.5
(anonymous) @ <embedded>:180187
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:2382 WebSocket connection to 'wss://ws.pusherapp.com/app/b811f48a038c1ff10b2f?protocol=7&client=js&version=2.2.3&flash=false' failed: Invalid frame header
getSocket @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:2382
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:117 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}
Pusher.warn @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:117
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:2382 WebSocket connection to 'wss://ws.pusherapp.com/app/b811f48a038c1ff10b2f?protocol=7&client=js&version=2.2.3&flash=false' failed: Invalid frame header
getSocket @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:2382
index.html:1 WebSocket connection to 'wss://ws.pusherapp.com/app/b811f48a038c1ff10b2f?protocol=7&client=js&version=2.2.3&flash=false' failed: WebSocket is closed before the connection is established.
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:117 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}
Pusher.warn @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:117
6C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'http://js.pusher.com/2.2.3/xhr.js' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'https://stats.pusher.com/timeline/v2/jsonp/1?session=NzY1NjYyNDQx&bundle=MQ…NpZCI6OSwic3RhdGUiOiJjbG9zZWQiLCJ0aW1lc3RhbXAiOjE1MDQ1NDY3NzEwNjV9XQ%3D%3D' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
2C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'http://js.pusher.com/2.2.3/xhr.js' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'https://stats.pusher.com/timeline/v2/jsonp/2?session=NzY1NjYyNDQx&bundle=MQ…0seyJjaWQiOjExLCJzdGF0ZSI6ImNsb3NlZCIsInRpbWVzdGFtcCI6MTUwNDU0NjgzMTA2OH1d' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
2C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'http://js.pusher.com/2.2.3/xhr.js' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'https://stats.pusher.com/timeline/v2/jsonp/3?session=NzY1NjYyNDQx&bundle=MQ…0seyJjaWQiOjEzLCJzdGF0ZSI6ImNsb3NlZCIsInRpbWVzdGFtcCI6MTUwNDU0Njg5MTA2OH1d' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
2C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'http://js.pusher.com/2.2.3/xhr.js' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'https://stats.pusher.com/timeline/v2/jsonp/4?session=NzY1NjYyNDQx&bundle=MQ…0seyJjaWQiOjE1LCJzdGF0ZSI6ImNsb3NlZCIsInRpbWVzdGFtcCI6MTUwNDU0Njk1MTA3MH1d' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1295
sendJSONP @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1427
prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1377
prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1429
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:150
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:282
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:241
2C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'http://js.pusher.com/2.2.3/xhr.js' because it violates the following Content Security Policy directive: "script-src 'self'".

prototype.send @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051
prototype.load @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1131
prototype.initialize @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:2120
prototype.connect @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1947
prototype.connect @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1737
prototype.tryStrategy @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1840
tryNextStrategy @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1792
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1836
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:271
(anonymous) @ C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:241
C:\Users\ZateFeto BDK\.atom\packages\atom-pair\lib\pusher\pusher.js:1051 Refused to load the script 'https://stats.pusher.com/timeline/v2/jsonp/5?session=NzY1NjYyNDQx&bundle=MQ…0seyJjaWQiOjE3LCJzdGF0ZSI6ImNsb3NlZCIsInRpbWVzdGFtcCI6MTUwNDU0NzAxMTA3M31d' because it violates the following Content Security Policy directive: "script-src 'self'".

**Comment by kn100** [comment]
Hi,

We don't officially support using your own app for this, however if you really want to, you only need one pusher app and it needs to be shared across both pcs, and either on MT1 or the source modified so you can specify the cluster
