### ISSUE TITLE
pair buddy not showing in different colors

### ISSUE THREAD

**Issue by otavio** [pusher/atom-pair#26]
We are testing the atom-pair extension and the connection join has worked very well. The remaining issue we are having is that the pair buddy didn't show (coloured) in the buffer. So we don't get its location and movements.

We receive its edits though, so just the cursor is not working fine.

How we can provide more information to hunt this bug?

**Comment by snollygolly** [comment]
Do you ever see the colors?  If you share a blank file does it work?  When I share a blank file locally and pair up, this is what I see (across both windows).

![screen shot 2015-03-14 at 3 04 50 pm](https://cloud.githubusercontent.com/assets/4993074/6653334/a1737b18-ca5b-11e4-99e8-6ff45b0740d6.png)

Do you see something different?

**Comment by otavio** [comment]
No; both looks grey. One information that might help... we are using Linux (even though this shouldn't) matter.

**Comment by snollygolly** [comment]
What version of Atom and atom-pair are you using?

**Comment by otavio** [comment]
Pair is 1.0.1 but atom I'm not sure as I'm not near the pc right now.

**Comment by otavio** [comment]
The Atom version is 0.152.0.

**Comment by snollygolly** [comment]
Full disclosure, I'm not the author of this package, but I've contributed a little bit to it, so there very well might be an issue regarding the colors.

That being said, you're a number of versions behind on Atom.  Could you update to the latest version of Atom (0.187.0), try again, and see if that makes any difference?

Thanks!

**Comment by jpatel531** [comment]
Aha, I've just had a look, and it does seem like there is an issue with the colours. I'm on it!

**Comment by jpatel531** [comment]
This resolution will come in the next patch, for sure :)
