### ISSUE TITLE
swallows the escape key

### ISSUE THREAD

**Issue by despairblue** [pusher/atom-pair#28]
The escape key is swallowed even if there is no atom-pair shared buffer open.

![screenshot from 2015-03-20 10 27 40](https://cloud.githubusercontent.com/assets/927609/6748953/c10f3ea0-ceeb-11e4-9fe7-4f142633a333.png)

**Comment by despairblue** [comment]
Ha, I was wondering for days why closing palettes with the escape key wouldn't return the focus to the buffer. It's this :D

Not trying to be mean, I'm just happy I found the cause. Clicking the buffer every time I used the escape key was driving me nuts :D

**Comment by jpatel531** [comment]
Thanks for bringing this to my attention!!

It looks like, when I created the settings page, I had to keep the package always 'active', i.e. not bound to activation commands. This meant 'AtomPair:hide views' was always open.

I made each view able to listen to 'core:cancel' (the inbuilt atom escape-key event) by creating an `AtomPairView` class, from which each view inherits.
