### ISSUE TITLE
Joining a session nukes currently open file.

### ISSUE THREAD

**Issue by johnhaley81** [pusher/atom-pair#3]
When I join a session that my friend has it will overwrite whatever file I currently have open with the contents of their file.

Maybe open a new file instead?

**Comment by jpatel531** [comment]
Ah yeah, I was aware of this but forgot to put it in the readme. Now you mention it, it would probably more convenient for a new tab to be opened.

Thanks for your feedback :)

**Comment by jpatel531** [comment]
v 0.29.0 released :)

**Comment by johnhaley81** [comment]
You guys rock :)
