### ISSUE TITLE
Not an Issue just a feature req

### ISSUE THREAD

**Issue by iheartkode** [pusher/atom-pair#40]
When you are in a pair, you have the bar with the info in front of the editor, could you relocate it or hide it. It's in the way of the first few lines of code. :)

**Comment by jpatel531** [comment]
Ah! You mean the bar saying 'Your pair buddy has joined the session' etc.? If you click on it and press escape, does it go? Maybe I should add a hotkey to remove these views - atm it's just escape (but that's only if it's focussed on)

**Comment by iheartkode** [comment]
Ahh, I will try that. Maybe have some text at the bottom saying to close this: "click it and hit esc" :)

**Comment by iheartkode** [comment]
or maybe a little x to close it :)

**Comment by jpatel531** [comment]
Thanks for the request! :)

**Comment by jpatel531** [comment]
1.1.5 has this feature :)

**Comment by iheartkode** [comment]
Awesome!
