### ISSUE TITLE
Copy pasting code pastes it twice

### ISSUE THREAD

**Issue by adamreisnz** [pusher/atom-pair#48]
Maybe atom-pair is not playing nicely with other plugins, but whenever I past code into the window with an atom-pair session active, the copied code is pasted twice.

This is on Mac OS X 10.10.3 with Atom 0.209.0

**Comment by jpatel531** [comment]
Hi Adam! Thanks for raising this with me - I'll have a look later. I suspect it may be down to the custom-paste I implemented, to help deal with synchronizing large copy-pasted chunks among clients.

**Comment by jpatel531** [comment]
Hey Adam - how does it look on the newest version of Atom?

**Comment by adamreisnz** [comment]
Unfortunately no, it still copy pastes twice. Both of us using the newest Atom version.
