### ISSUE TITLE
Can't enter configuration keys or start new session

### ISSUE THREAD

**Issue by alsoicode** [pusher/atom-pair#5]
I created a new Pusher account and [installed atom-pair through apm](https://blog.pusher.com/atom-pair/) on Ubuntu 14.04 in Atom 0.143.0.

When I attempt to enter my Pusher configuration keys, by choosing: 

```
AtomPair: Set configuration keys
```

from the command palette, nothing happens. AtomPair ceases to be displayed in the command palette after that. Attempting to start a pairing session by choosing:

```
AtomPair: Start new sharing session
```

also results in the same behavior. I do not receive a session id, and AtomPair disappears from the command palette.

I ended up having to un-install and re-install Atom completely in order to use the package.

**Comment by jpatel531** [comment]
Hi there. Sorry about that! By uninstall and reinstall, did it update the Atom version? I haven't tested this out for older versions of Atom - so there might be newer versions of the API the package depends on

**Comment by alsoicode** [comment]
Re-installing bumped the version to 0.177.0, so that was probably part of it. I had quite a few extra packages installed, which I tried disabling first, but to no avail. I can't wait to try this out today once my colleagues get online, especially via HipChat :)
