### ISSUE TITLE
Support for multiple open tabs?

### ISSUE THREAD

**Issue by adamreisnz** [pusher/atom-pair#50]
Does atom-pair have support or is support planned for multiple open tabs or working together in multiple files at once?

**Comment by jpatel531** [comment]
It's definitely something I've been considering, and would like to work on as soon as I have the time, for sure

**Comment by iamtmrobinson** [comment]
:+1: for this feature.

**Comment by rogerkk** [comment]
This would be cool! It's unfortunately not often that we are working on only a single file. :(

**Comment by jpatel531** [comment]
Yeah totally - there's definitely ways to implement it. I was having a think over the weekend, and trying to address the issue of how/if to share a session across multiple tabs, and also how the user can control what's shared. Definitely want to do this though!

**Comment by rogerkk** [comment]
Awesome, can't wait. Great work so far.

**Comment by jpatel531** [comment]
Thanks! This is currently in development - I've got a working example of multiple tab sharing, having redesigned the whole package (which I'm glad of!). Just need to flesh out edge cases and tighten things up

**Comment by adamreisnz** [comment]
Nice, hope to see it in action soon.

**Comment by jpatel531** [comment]
Version 2 is released with this capability - feel free to reopen this issue if something unexpected happens!

**Comment by adamreisnz** [comment]
Great, will give it a try soon!
