### ISSUE TITLE
Can't get session to start

### ISSUE THREAD

**Issue by mark-reason** [pusher/atom-pair#51]
When I put in the session ID Atom just opens a new tab but doesn't show anything else.

I'm am trying to start the session on windows and pass to a mac, would this cause issues?

**Comment by jpatel531** [comment]
Hi there - I'll have a look at this as soon as I can. Thanks for raising this!

**Comment by csshugs** [comment]
@mark-reason 
I just ran into the same issue, although I was just simulating it on my own (Windows) Computer with two editor-windows open. What I didn't know was I had to "Enable client events" in the app settings in pusher. Enabling that fixed it for me.

**Comment by jpatel531** [comment]
Can I close this, @mark-reason ? Does this issue persist?

**Comment by mark-reason** [comment]
Yeh this can be closed, cheers.
