### ISSUE TITLE
Can't download version 3.0.0

### ISSUE THREAD

**Issue by nightscape** [pusher/atom-pair#54]
Atom tells me that atom-pair can be updated to 3.0.0, but can't download the file from https://www.atom.io/api/packages/atom-pair/versions/3.0.0/tarball.
The website also only mentions 2.0.0.
Which one is correct?

Thanks!
  Martin

**Comment by jpatel531** [comment]
Hi there! 2.0.0 is correct. There were some versioning issues later and I accidentally ended up publishing 3.0.0, which has been retracted. Maybe try restarting atom? Or just `apm update atom-pair` ?

**Comment by nightscape** [comment]
I tried apm update and restarting Atom, both still give me 3.0.0...
I've also searched through ~/.atom in the hope that there might be some cached file that just has to be deleted, but didn't find anything so far...

**Comment by nightscape** [comment]
I also just tried starting with `atom --safe` and removing `~/.atom/storage` didn't help either...

**Comment by jpatel531** [comment]
Ah! try `apm install atom-pair@2.0.0`

**Comment by jpatel531** [comment]
Apologies for the mixups - there might be some caching on apm's side of things

**Comment by nightscape** [comment]
Ok, manually specifying the version worked. Atom still shows the update for 3.0.0 which I'll ignore until that day arrives ;))
Thanks for your help!
