### ISSUE TITLE
Failed to download 3.0.0

### ISSUE THREAD

**Issue by ryanaltvater** [pusher/atom-pair#55]
I'm running into a couple issues where it's saying 2.0.0 is out of date and I need the latest 3.0.0, but it doesn't exist.

```
Updating to “atom-pair@3.0.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/atom-pair/versions/3.0.0/tarball: 404 Not Found Not found
```

**Comment by jpatel531** [comment]
Ah yeah - this is a temporary issue related to #54 

Just run, `apm install atom-pair@2.0.0`

Apologies for the inconvenience, and thanks for raising an issue!

**Comment by ryanaltvater** [comment]
I already have 2.0.0 installed and it's asking me to update to 3.0.0 still, even after running that command again and restarting. I get the following error message after starting a new session.

![screen shot 2015-08-04 at 10 23 08 am](https://cloud.githubusercontent.com/assets/1336787/9062864/d6af7bea-3a92-11e5-9268-9037be3db801.png)

**Comment by jpatel531** [comment]
Oh gee - never seen that before. I've just published v2.0.1 - an arbitrary release that will hopefully invalidate some cache. Let me know how it goes :/

**Comment by ryanaltvater** [comment]
The update resolved the error issue after restarting, but now my coworker can't see any of my files. We found your plugin this morning and tested it out. Everything seemed to work fine. Now we're both on 2.0.1 and I get a notification that he comes and goes, but on he doesn't see any of my files on his screen once he has joined the session.

**Comment by ryanaltvater** [comment]
UPDATE: I'm able to connect to him and see a shared file, but he can't see my file when he connects to me.

**Comment by jpatel531** [comment]
Are there any logs in the atom chrome console? (cmd+alt+i)? Could you copy paste them here?

**Comment by ryanaltvater** [comment]
His editor or mine?

**Comment by ryanaltvater** [comment]
MINE:

```
/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher-js-client-auth.js:111 You are using PusherJS client authentication. Never ever use this for a production application, as it would expose your secret keys.
/Users/raltvater/.atom/packages/emmet/lib/emmet.coffee:133 Loading Emmet extensions from ~/emmet
/Users/raltvater/.atom/packages/emmet/lib/emmet.coffee:150 Emmet: no such extension folder: /Users/raltvater/emmet
index.js:56 Window load time: 2106ms
/Users/raltvater/.atom/packages/sync-settings/lib/sync-settings.coffee:60 checking latest backup...
/Users/raltvater/.atom/packages/sync-settings/lib/sync-settings.coffee:299 Creating GitHubApi client with token = 44609c20ed2712c865d44cfb69ede34f4bae4b71
/Users/raltvater/.atom/packages/sync-settings/lib/tracker.coffee:71 tracking Activate
/Users/raltvater/.atom/packages/sync-settings/lib/sync-settings.coffee:66 null Object
/Users/raltvater/.atom/packages/sync-settings/lib/sync-settings.coffee:81 latest backup version 95888deeeeece14475de1682156f537eb763e5ec
5/Users/raltvater/.atom/packages/pigments/lib/color-buffer.coffee:242 This ColorBuffer is already destroyed
/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:1037 Refused to load the script 'http://stats.pusher.com/timeline/v2/jsonp/1?session=OTExNDEwODc2&bundle=MQ%…Jzb2NrZXRfaWQiOiI0ODExMy4zNjI2NjY0In0sInRpbWVzdGFtcCI6MTQzODY5OTM2MzQ3M31d' because it violates the following Content Security Policy directive: "script-src 'self'".

/Users/raltvater/.atom/packages/atom-pair/lib/atom_pair.coffee:308 new sharepane cause new tab
13/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:114 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"To send client events, you must enable this feature in the Settings page of your dashboard."}}}
/Users/raltvater/.atom/packages/atom-pair/lib/atom_pair.coffee:329 disconnect
/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:1037 Refused to load the script 'http://stats.pusher.com/timeline/v2/jsonp/2?session=OTk0MzEzODU5&bundle=MQ%…Y2tldF9pZCI6IjQ4MTA1LjM2Mjk5MzIifSwidGltZXN0YW1wIjoxNDM4Njk5NjY1MTY1fV0%3D' because it violates the following Content Security Policy directive: "script-src 'self'".

12/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:114 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"To send client events, you must enable this feature in the Settings page of your dashboard."}}}
/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:1037 Refused to load the script 'http://stats.pusher.com/timeline/v2/jsonp/3?session=NTg1Mjc5OTg5&bundle=MQ%…Y2tldF9pZCI6IjQ4MTUzLjM2NDQwMDAifSwidGltZXN0YW1wIjoxNDM4NzAwMDc1MzkzfV0%3D' because it violates the following Content Security Policy directive: "script-src 'self'".
/Users/raltvater/.atom/packages/atom-pair/lib/pusher/pusher.js:1037 prototype.send
```

**Comment by ryanaltvater** [comment]
HIS:

```
Refused to load the script 'http://stats.pusher.com/timeline/v2/jsonp/2?session=Mzk0OTY1Njg3&bundle=MQ%…Y2tldF9pZCI6IjQ4MDg1LjM2NjMxOTIifSwidGltZXN0YW1wIjoxNDM4NzAwMjYzMDI1fV0%3D' because it violates the following Content Security Policy directive: "script-src 'self'".
```

**Comment by jpatel531** [comment]
the stats error is expected. if you have your own account you need to go to dashboard.pusher.com and enable client events. I'll add this to the README

**Comment by ryanaltvater** [comment]
Where is this located on the dashboard?

**Comment by ryanaltvater** [comment]
Found it.

**Comment by jpatel531** [comment]
if on dashboard.pusher.com you click an app -> then on the left you to go settings -> then 'enable client events' and try again

**Comment by jpatel531** [comment]
ah cool!

**Comment by ryanaltvater** [comment]
I just noticed that my coworker doesn't have his own Pusher account with key and secret. Might that have anything to do with it?

**Comment by jpatel531** [comment]
nope, that should be fine. As long as you have one that's enough. Are the problems still persisting? Even with client events turned on?

**Comment by ryanaltvater** [comment]
He was able to connect to me. It opened about 5-6 "untitled" files representing the 5-6 files I have open on my screen. For him, they were all blank except the last tab which is a JS file. For him, he could only see the bottom part of the file and it was unhighlighted. I'm assuming it was unhighlighted because it was registered as "untitled" with no filetype associated with what he was able to view.

**Comment by jpatel531** [comment]
ahhhh i now see the issue, and i'm working on a fix. I'll reply as soon as I've sorted this out

**Comment by jpatel531** [comment]
Hold on, if you start with one file --> start the session + invite your friend --> then open all the other files you need, does it have the desired effect?

**Comment by ryanaltvater** [comment]
Tested it out between my personal computer and work computer and it seems to work fine. The only issue now is that the person connecting to the session has to re-save all the files that get opened, to their respective locations if you're working on the same project together (since they get opened as new/untitled documents). Pretty slick though, regardless.

**Comment by jpatel531** [comment]
ah yeah for sure - i'll bear that in mind! i'm glad it's finally working! thanks! and i'll get to workin on your other issues -- thanks for making them :)

**Comment by ryanaltvater** [comment]
Thank you for the immediate support and feedback. :)

**Comment by nandinisgr** [comment]
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"To send client events, you must enable this feature in the Settings page of your dashboard."}}}
