### ISSUE TITLE
Start/Join new session issue and feature request

### ISSUE THREAD

**Issue by ryanaltvater** [pusher/atom-pair#56]
It would be nice to be able to start/join a session inside the same Atom window where you may have an active session already. Currently, you have to close the Atom window to kill a session, before starting/joining a new session.

This may seem far-fetched but even having multiple sessions would be cool.

**Comment by benhalverson** [comment]
:+1:

**Comment by jpatel531** [comment]
You could always open a new window `cmd/ctrl+shift+n` to start a new session. What are the use cases for having multiple sessions within one window? I'm curious!
