### ISSUE TITLE
Un-sync Buddie Scrolling

### ISSUE THREAD

**Issue by DanielTamkin** [pusher/atom-pair#70]
When Pairing with another person, you follow wherever they're window goes. I'd like to be able to work on the top of a file while on the bottom the other person work away.

**Comment by jpatel531** [comment]
Fair! I was meaning to get rid of that anyway. I'll publish a patch soon

**Comment by DanielTamkin** [comment]
Thanks @jpatel531 :+1:

**Comment by jpatel531** [comment]
2.0.6 released!
