### ISSUE TITLE
When a new tab is opened, multiple tabs open on the paired session.

### ISSUE THREAD

**Issue by hackeryarn** [pusher/atom-pair#71]
This behavior seems to be somewhat inconsistent. Sometimes I get a duplicate tab, and other times its just blank tabs.

I have been able to recreate this on local and remote pairing sessions.

**Comment by ghost** [comment]
:+1: Also seeing this

**Comment by ghost** [comment]
The behavior may be related to switching files. I shared a session with a friend remotely, and when the session started there were only the expected tabs on his end. I opened another file, and his machine got flooded with tabs that eventually all became copies of the file I’d opened.

**Comment by hackeryarn** [comment]
Yup, also I noticed if you click on an opened file in your file tree, it opens up another copy of the file on the paired machine.

**Comment by DanielTamkin** [comment]
Same thing happens to me, not totally annoying but would be nice to see fixed soon.

**Comment by jpatel531** [comment]
Thanks for raising this! - I'll try to address this in the next release.

**Comment by DanielTamkin** [comment]
Thanks @jpatel531 :+1:
