### ISSUE TITLE
Read me image broken

### ISSUE THREAD

**Issue by Depapepe** [pusher/atom-pair#72]
<img width="868" alt="2015-08-17 4 55 04" src="https://cloud.githubusercontent.com/assets/8286620/9300436/decceaa6-4500-11e5-922e-7bd46a3f2d37.png">

<img width="1010" alt="2015-08-17 5 20 09" src="https://cloud.githubusercontent.com/assets/8286620/9300748/456601aa-4504-11e5-97e2-df6596b7283d.png">

Hi, i'm a big fan of yours. I found some error in readme file. The Images in readme are broken, because they were written in relative paths.

I think it is needed to modify.

So I have been modified with Github row paths instead of relative path in my fork repository. 

if you allow the pull request, I will send it.

Wait for your answer.

**Comment by jpatel531** [comment]
Ah I see. Thanks for bringing this to my attention. Feel free to submit a PR, for sure

**Comment by jpatel531** [comment]
Actually I'll just fix it quickly

**Comment by Depapepe** [comment]
I know, it's very simple. I hope accept my PR.
