### ISSUE TITLE
Can't invite my buddy behind proxy. 

### ISSUE THREAD

**Issue by ikaruce** [pusher/atom-pair#74]
First, I wanna say thank you. 
This is very helpful to work together with my buddies because of you.

I wanna use in my office with my colleagues but I can't.
I guess that because network behind proxy. Do you have any idea how to use behind proxy?

**Comment by jpatel531** [comment]
Hi there! Could you open up your atom chrome inspector (command/ctrl + alt + i) and ping me back with what it says?

**Comment by jpatel531** [comment]
2.0.8 should have SSL on by default, so the proxy shouldn't touch the network traffic between pair-ers. Let me know if this helps!

**Comment by ikaruce** [comment]
I tried just now, but I can't invite anybody at 2.0.9, 

There're some messages in inspecter 
`Refused to load the script 
'https://stats.pusher.com/timeline/v2/jsonp/2?session=Njk5NzExNDkz&bundle=MQ…fSx7InN0YXRlIjoiZGlzY29ubmVjdGVkIiwidGltZXN0YW1wIjoxNDQwNzI2ODg4MTk2fV0%3D' 
because it violates the following Content Security Policy directive:
 "script-src 'self'".`

Thank you for your efforts.

**Comment by jpatel531** [comment]
Hmm that error is normal and doesn't affect functionality. (It's because Atom, understandably, forbids dynamically linking in external scripts - and so we can't collect details stats).

Could you just double-check client-events are enabled for your Pusher app, if you're not using the default one?

**Comment by jpatel531** [comment]
Also, how are you inviting them? Pasting them the session ID or over Slack/HipChat?

**Comment by ikaruce** [comment]
It Works after my colleague updated version 2.0.9. !! 

Thank you
