### ISSUE TITLE
No settings option on 2.0.6

### ISSUE THREAD

**Issue by raymondhardy** [pusher/atom-pair#75]
Updated to 2.0.6 and there is no longer a settings option. Reverted back to 2.0.5 and it is back. I am unable to update to 2.0.6 at this time.

**Comment by ikaruce** [comment]
I got a same situation. 
@raymondhardy Can you tell me how to revert back ?

**Comment by raymondhardy** [comment]
Uninstall the plugin
Close atom
Then run the following command from command line. (You need atom command
line tools installed)
apm install atom-pair@2.0.5

**Comment by jpatel531** [comment]
Sorry about that! When I separated out the 'Session' object from the main module, I accidentally took the settings page along with it, when it has to be part of the main module. 2.0.7 should resolve this
