### ISSUE TITLE
Fresh install throws pusher errors

### ISSUE THREAD

**Issue by tarwich** [pusher/atom-pair#77]
When you start a new pairing session after a fresh install, you get pusher errors.

First, I installed...

`apm install atom-pair`

Then opened `atom`
Then used the "AtomPair: Start a new pairing session" command
![image](https://cloud.githubusercontent.com/assets/334149/9498301/ac0c0c20-4bde-11e5-933d-4224b5211859.png)

And I got this error
![image](https://cloud.githubusercontent.com/assets/334149/9498329/dbf03d26-4bde-11e5-9d80-b0ef49664e12.png)

```
Mac OS X 10.10.3.14D136:
  arch: x86_64
Atom:
  version: 1.0.7
  architecture: x86_64
```

**Comment by jpatel531** [comment]
Hi there! That's bizarre, the package should be using the default Pusher keys. On the settings page for the package, do you have any keys registered?

**Comment by raymondhardy** [comment]
Yeah i think this is also a problem with moving the settings. You can add the default keys in.
  "atom-pair":
    pusher_app_key: "d41a439c438a100756f5"
    pusher_app_secret: "4bf35003e819bb138249"

You can get to the settings by clicking on the box from the plugin screen the settings are listed below

**Comment by xuebingli** [comment]
I am experiencing this error as well. This error still appears even after I manually add my own Pusher key and secret to the plugin's config file.

**Comment by jpatel531** [comment]
Copied from #78  : 

Hi there - 2.0.9 should resolve this. I realize that I was only merging the main module with the config options only when the package was activated, meaning you couldn't see them in your settings page pre-activation. It should be fine now, hopefully :/ apologies!

**Comment by xuebingli** [comment]
Thank you for fixing it @jpatel531

**Comment by atroche** [comment]
nice!

**Comment by tarwich** [comment]
This is fixed for me on Windows.
I don't have access to my Mac until Wed.

Thanks!
