### ISSUE TITLE
Still no settings

### ISSUE THREAD

**Issue by raymondhardy** [pusher/atom-pair#78]
This is  still an issue https://github.com/pusher/atom-pair/issues/75
screenshot of 1.0.8 no settings. I have tried uninstalling and reinstalling. restarting atom. I also tried 1.0.7

Thanks
![screen shot 2015-08-26 at 10 45 40 am](https://cloud.githubusercontent.com/assets/1498519/9501392/00cc4a9e-4be0-11e5-8396-f2d61a264c76.png)

**Comment by raymondhardy** [comment]
I found the settings listed if you click on the box that has atom-pair but it only has the pusher_app_key and pusher_app_secret fields.

**Comment by jpatel531** [comment]
Hi there - 2.0.9 should resolve this. I realize that I was only merging the main module with the config options _only_ when the package was activated, meaning you couldn't see them in your settings page pre-activation. It should be fine now, hopefully :/ apologies!
