### ISSUE TITLE
Screens get out of sync

### ISSUE THREAD

**Issue by jeremykay** [pusher/atom-pair#91]
This has happened to me multiple times with multiple users - in fact I never was able to get this plugin working correctly. I'm on atom-par 2.0.10 and atom 1.0.19 on mac os.

After a few minutes of pairing, the code would get out of sync between our machines. I would see the code on my end garbled but the other user would see the code as perfectly fine. I had to resort to copy/pasting via another chat client.

Has anyone successfully used this plugin for more than 10 minutes reliably?

**Comment by jpatel531** [comment]
Hi there - thanks for raising this issue. I've come across this - where pairing for more than a few minutes, there might be one missed message (which leads to a knock on effect). Currently testing out a few strategies for solving this. One is introducing a server to ensure synchronization. Another is to introduce a concept of 'read receipts' - so one client sends a message back to the other whenever a message has been received. If not, the "leader" (i.e. first person in the session) shares over the file contents. This _would_ ensure consistency. When I get some free time I'll be sure to prioritize this stuff. Let me know if you have any suggestions :)

**Comment by jeremykay** [comment]
Thanks for your response. The "read receipts" idea sounds promising and likely not terribly complicated to implement (although it could introduce lag and overhead). I do like it more than a server idea because a third party wouldn't need to get involved.
