### ISSUE TITLE
Buffers out of sync. Possible way to reproduce.

### ISSUE THREAD

**Issue by davibe** [pusher/atom-pair#95]
I tried atom-pair with @crisbit. We were in the same office. We shared one file. I started adding new lines  (~20) at the top of the file then stared deleting them. While i was deleting the newlines my colleague did some UNDO (cmd+z). We ended up with 2 different buffers on the screen. This breaks consistency, badly. It should not be possible.

**Comment by jpatel531** [comment]
Hi there. I've experienced this too. I'm working on a branch that detects
inconsistency across clients. Next step is to call a resync. Last couple of
weeks I'd been shy about releasing it as performance had been seriously
affected, but that no longer seems an issue. Thanks for the steps!! I'll
try to get a release out asap
